variables:
  # Common variables to be able to build and push docker images
  # https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-disabled
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  # Hardhat variables
  INFURA_API_KEY: "zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"
  MNEMONIC: "here is where your twelve words mnemonic should be put my friend"

cache:
  paths:
    - node_modules/

stages:
  - sanity-checks
  - test

.install-deps: &install-deps
  - npm install

image: atixlabs/node:12.18.1-alpine-build

lint:
  stage: sanity-checks
  script:
    - *install-deps
    - npm run lint

test:
  stage: test
  script:
    - *install-deps
    - npm run test
  except:
    refs:
      # Quick checks on regular branches
      - master
      - develop
      - /^release.*$/
      - /^hotfix.*$/

coverage:
  stage: test
  script:
    - *install-deps
    - npm run coverage
  artifacts:
    reports:
      cobertura: coverage/cobertura-coverage.xml
  only:
    refs:
      # Only run on master, develop, release/x.y.x and hotfix/xxxx
      - master
      - develop
      - /^release.*$/
      - /^hotfix.*$/
