/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Autopetrified, AutopetrifiedInterface } from "../Autopetrified";

const _abi = [
  {
    constant: true,
    inputs: [],
    name: "hasInitialized",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getInitializationBlock",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "isPetrified",
    outputs: [
      {
        name: "",
        type: "bool",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610022640100000000610027810204565b610230565b610038640100000000610127810204565b60408051808201909152601881527f494e49545f414c52454144595f494e495449414c495a4544000000000000000060208201529015610110576040517f08c379a00000000000000000000000000000000000000000000000000000000081526004018080602001828103825283818151815260200191508051906020019080838360005b838110156100d55781810151838201526020016100bd565b50505050905090810190601f1680156101025780820380516001836020036101000a031916815260200191505b509250505060405180910390fd5b50610125600019640100000000610152810204565b565b600061014d6000805160206103a383398151915264010000000061013061022882021704565b905090565b610163640100000000610127810204565b60408051808201909152601881527f494e49545f414c52454144595f494e495449414c495a45440000000000000000602082015290156101ff576040517f08c379a0000000000000000000000000000000000000000000000000000000008152600401808060200182810382528381815181526020019150805190602001908083836000838110156100d55781810151838201526020016100bd565b506102256000805160206103a38339815191528264010000000061013461022c82021704565b50565b5490565b9055565b6101648061023f6000396000f3006080604052600436106100565763ffffffff7c01000000000000000000000000000000000000000000000000000000006000350416630803fac0811461005b5780638b3dd74914610084578063de4796ed146100ab575b600080fd5b34801561006757600080fd5b506100706100c0565b604080519115158252519081900360200190f35b34801561009057600080fd5b506100996100e9565b60408051918252519081900360200190f35b3480156100b757600080fd5b50610070610119565b6000806100cb6100e9565b905080158015906100e35750806100e061012c565b10155b91505090565b60006101147febb05b386a8d34882b8711d156f463690983dc47815980fb82aeeff1aa43579e610130565b905090565b60006000196101266100e9565b14905090565b4390565b5490565b90555600a165627a7a723058206a1efe8d06a613fc114f381ef746daa2ce81ea08cd76129257bb3546dd3fc1e60029ebb05b386a8d34882b8711d156f463690983dc47815980fb82aeeff1aa43579e";

export class Autopetrified__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Autopetrified> {
    return super.deploy(overrides || {}) as Promise<Autopetrified>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Autopetrified {
    return super.attach(address) as Autopetrified;
  }
  connect(signer: Signer): Autopetrified__factory {
    return super.connect(signer) as Autopetrified__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AutopetrifiedInterface {
    return new utils.Interface(_abi) as AutopetrifiedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Autopetrified {
    return new Contract(address, _abi, signerOrProvider) as Autopetrified;
  }
}
