/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IAragonFundraisingController,
  IAragonFundraisingControllerInterface,
} from "../IAragonFundraisingController";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_collateral",
        type: "address",
      },
    ],
    name: "collateralsToBeClaimed",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      {
        name: "_token",
        type: "address",
      },
    ],
    name: "updateTappedAmount",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "openTrading",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      {
        name: "_who",
        type: "address",
      },
      {
        name: "_token",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IAragonFundraisingController__factory {
  static readonly abi = _abi;
  static createInterface(): IAragonFundraisingControllerInterface {
    return new utils.Interface(_abi) as IAragonFundraisingControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAragonFundraisingController {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAragonFundraisingController;
  }
}
