/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMarketMaker, IMarketMakerInterface } from "../IMarketMaker";

const _abi = [
  {
    constant: true,
    inputs: [
      {
        name: "_collateral",
        type: "address",
      },
    ],
    name: "getCollateralToken",
    outputs: [
      {
        name: "",
        type: "bool",
      },
      {
        name: "",
        type: "uint256",
      },
      {
        name: "",
        type: "uint256",
      },
      {
        name: "",
        type: "uint32",
      },
      {
        name: "",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];

export class IMarketMaker__factory {
  static readonly abi = _abi;
  static createInterface(): IMarketMakerInterface {
    return new utils.Interface(_abi) as IMarketMakerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMarketMaker {
    return new Contract(address, _abi, signerOrProvider) as IMarketMaker;
  }
}
