/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IMynt, IMyntInterface } from "../IMynt";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_account",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMynt__factory {
  static readonly abi = _abi;
  static createInterface(): IMyntInterface {
    return new utils.Interface(_abi) as IMyntInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IMynt {
    return new Contract(address, _abi, signerOrProvider) as IMynt;
  }
}
