/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface DAOFactoryInterface extends ethers.utils.Interface {
  functions: {
    "baseACL()": FunctionFragment;
    "newDAO(address)": FunctionFragment;
    "regFactory()": FunctionFragment;
    "baseKernel()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "baseACL", values?: undefined): string;
  encodeFunctionData(functionFragment: "newDAO", values: [string]): string;
  encodeFunctionData(
    functionFragment: "regFactory",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "baseKernel",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "baseACL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "newDAO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "regFactory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseKernel", data: BytesLike): Result;

  events: {
    "DeployDAO(address)": EventFragment;
    "DeployEVMScriptRegistry(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DeployDAO"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DeployEVMScriptRegistry"): EventFragment;
}

export class DAOFactory extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: DAOFactoryInterface;

  functions: {
    baseACL(overrides?: CallOverrides): Promise<[string]>;

    newDAO(
      _root: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    regFactory(overrides?: CallOverrides): Promise<[string]>;

    baseKernel(overrides?: CallOverrides): Promise<[string]>;
  };

  baseACL(overrides?: CallOverrides): Promise<string>;

  newDAO(
    _root: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  regFactory(overrides?: CallOverrides): Promise<string>;

  baseKernel(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    baseACL(overrides?: CallOverrides): Promise<string>;

    newDAO(_root: string, overrides?: CallOverrides): Promise<string>;

    regFactory(overrides?: CallOverrides): Promise<string>;

    baseKernel(overrides?: CallOverrides): Promise<string>;
  };

  filters: {
    DeployDAO(dao?: null): TypedEventFilter<[string], { dao: string }>;

    DeployEVMScriptRegistry(
      reg?: null
    ): TypedEventFilter<[string], { reg: string }>;
  };

  estimateGas: {
    baseACL(overrides?: CallOverrides): Promise<BigNumber>;

    newDAO(
      _root: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    regFactory(overrides?: CallOverrides): Promise<BigNumber>;

    baseKernel(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    baseACL(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    newDAO(
      _root: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    regFactory(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    baseKernel(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
