/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface TapDisabledInterface extends ethers.utils.Interface {
  functions: {
    "updateMaximumTapRateIncreasePct(uint256)": FunctionFragment;
    "updateBeneficiary(address)": FunctionFragment;
    "withdraw(address)": FunctionFragment;
    "updateTappedAmount(address)": FunctionFragment;
    "resetTappedToken(address)": FunctionFragment;
    "rates(address)": FunctionFragment;
    "addTappedToken(address,uint256,uint256)": FunctionFragment;
    "updateMaximumTapFloorDecreasePct(uint256)": FunctionFragment;
    "getMaximumWithdrawal(address)": FunctionFragment;
    "updateTappedToken(address,uint256,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "updateMaximumTapRateIncreasePct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateBeneficiary",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values: [string]): string;
  encodeFunctionData(
    functionFragment: "updateTappedAmount",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "resetTappedToken",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "rates", values: [string]): string;
  encodeFunctionData(
    functionFragment: "addTappedToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateMaximumTapFloorDecreasePct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaximumWithdrawal",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTappedToken",
    values: [string, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "updateMaximumTapRateIncreasePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateBeneficiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateTappedAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetTappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addTappedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateMaximumTapFloorDecreasePct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaximumWithdrawal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateTappedToken",
    data: BytesLike
  ): Result;

  events: {};
}

export class TapDisabled extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TapDisabledInterface;

  functions: {
    updateMaximumTapRateIncreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateBeneficiary(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateTappedAmount(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    resetTappedToken(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    rates(_token: string, overrides?: CallOverrides): Promise<[BigNumber]>;

    addTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    updateMaximumTapFloorDecreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMaximumWithdrawal(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    updateTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  updateMaximumTapRateIncreasePct(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateBeneficiary(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateTappedAmount(
    _token: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  resetTappedToken(
    arg0: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  rates(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

  addTappedToken(
    arg0: string,
    arg1: BigNumberish,
    arg2: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  updateMaximumTapFloorDecreasePct(
    arg0: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMaximumWithdrawal(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  updateTappedToken(
    arg0: string,
    arg1: BigNumberish,
    arg2: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    updateMaximumTapRateIncreasePct(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateBeneficiary(arg0: string, overrides?: CallOverrides): Promise<void>;

    withdraw(arg0: string, overrides?: CallOverrides): Promise<void>;

    updateTappedAmount(
      _token: string,
      overrides?: CallOverrides
    ): Promise<void>;

    resetTappedToken(arg0: string, overrides?: CallOverrides): Promise<void>;

    rates(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    addTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    updateMaximumTapFloorDecreasePct(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    getMaximumWithdrawal(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    updateMaximumTapRateIncreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateBeneficiary(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    withdraw(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateTappedAmount(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    resetTappedToken(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    rates(_token: string, overrides?: CallOverrides): Promise<BigNumber>;

    addTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    updateMaximumTapFloorDecreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMaximumWithdrawal(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    updateTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    updateMaximumTapRateIncreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateBeneficiary(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateTappedAmount(
      _token: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    resetTappedToken(
      arg0: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    rates(
      _token: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    addTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    updateMaximumTapFloorDecreasePct(
      arg0: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMaximumWithdrawal(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    updateTappedToken(
      arg0: string,
      arg1: BigNumberish,
      arg2: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
